### ISSUE TITLE
Index & Store Genotype field

### ISSUE THREAD

**Issue by meatcar** [phenotips/variant-store#19]
We need to index and store the Genotype field of a VCF, as well as some information on whether it's heterozygous or not. 
## Tasks
- [x] Parse the genotype field into a [`GACall`](http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/%2FUsers%2Fkeenan%2FDropbox%2Fgit-checkouts%2Fschemas%2Fsrc%2Fmain%2Fresources%2Favro%2Ftarget%2Fall.avpr/org.ga4gh.GACall), attach it to the `GAVariant`
- [x] Store the genotype field in Solr
- [x] Expose it to be queried

**Comment by meatcar** [comment]
As per discussion with @buske, we need to have Solr store a record per variant, not a record per position as it is at the moment. (Right now there are multiple alts per record, but we should have one.)

| CHROM | POS | REF | ALT | GT | **What to store** |
| --- | --- | --- | --- | --- | --- |
| 1 | 10 | C | T | 0/1 | 1:10C>T 1 copy |
| 1 | 10 | C | A,G | 1/2 | 1:10C>A 1 copy |
|  |  |  |  |  | 1:10C>G 1 copy |
| 1 | 10 | C | A | 1/1 | 1:10C>A 2 copies |
| 1 | 12 | A | AC,ACCC,ACCCC | 1/2   2/3     ... | records per variant per patient |

**Comment by meatcar** [comment]
we don't handle the last case as we don't accept multi-sample vcfs.

**Comment by meatcar** [comment]
Done with #24
